version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: wt
    binary: wt-bin
    main: ./cmd/wt
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# macOS universal binary
universal_binaries:
  - id: wt-universal
    ids:
      - wt
    replace: true

archives:
  - id: default
    name_template: >-
      wt_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: tobiase
    name: worktree-utils
  
  header: |
    ## Installation

    ### Quick install
    
    ```bash
    curl -fsSL https://raw.githubusercontent.com/tobiase/worktree-utils/main/get.sh | sh
    ```
    
    Or download specific platform archives below.

    ### Update existing installation
    If you already have wt installed, simply run:
    ```bash
    wt update
    ```

    ### Manual download
    Download the appropriate archive for your platform from the assets below.

  footer: |
    **Full Changelog**: https://github.com/tobiase/worktree-utils/compare/{{ .PreviousTag }}...{{ .Tag }}

# Announce releases
announce:
  skip: true