version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: wt
    binary: wt-bin
    main: ./cmd/wt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# macOS universal binary
universal_binaries:
  - id: wt-universal
    ids:
      - wt
    replace: true

archives:
  - id: wt
    name_template: >-
      wt_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: tobiase
    name: worktree-utils
  
  header: |
    ## Installation

    ### Quick install (macOS/Linux)
    ```bash
    # Download latest release for your platform:
    # macOS Intel
    curl -L https://github.com/tobiase/worktree-utils/releases/latest/download/wt_{{ .Version }}_Darwin_x86_64.tar.gz | tar xz
    
    # macOS Apple Silicon
    curl -L https://github.com/tobiase/worktree-utils/releases/latest/download/wt_{{ .Version }}_Darwin_arm64.tar.gz | tar xz
    
    # Linux x86_64
    curl -L https://github.com/tobiase/worktree-utils/releases/latest/download/wt_{{ .Version }}_Linux_x86_64.tar.gz | tar xz
    
    # Then install
    ./wt-bin setup
    ```

    ### Manual download
    Download the appropriate archive for your platform from the assets below.

  footer: |
    **Full Changelog**: https://github.com/tobiase/worktree-utils/compare/{{ .PreviousTag }}...{{ .Tag }}

# Announce releases
announce:
  skip: true