version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: wt
    binary: wt-bin
    main: ./cmd/wt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # macOS universal binary
    universal_binaries:
      - replace: true

archives:
  - id: wt
    name_template: >-
      wt_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: tobiase
    name: worktree-utils
  
  header: |
    ## Installation

    ### Quick install (macOS/Linux)
    ```bash
    # Download latest release
    curl -L https://github.com/tobiase/worktree-utils/releases/latest/download/wt_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz | tar xz
    
    # Install
    ./wt-bin setup
    ```

    ### Manual download
    Download the appropriate archive for your platform from the assets below.

  footer: |
    **Full Changelog**: https://github.com/tobiase/worktree-utils/compare/{{ .PreviousTag }}...{{ .Tag }}

# Announce releases
announce:
  skip: true